// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKGq_5zCeckS7oC3N4o7WUkFP-UD3A9w',
    appId: '1:496638177733:web:5ea9e846173c3c6fd71bac',
    messagingSenderId: '496638177733',
    projectId: 'reports-app-dc046',
    authDomain: 'reports-app-dc046.firebaseapp.com',
    storageBucket: 'reports-app-dc046.firebasestorage.app',
    measurementId: 'G-HZLFTX01LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48VmKtsO6fT1I3xww5G9mFwJN819OkXI',
    appId: '1:496638177733:android:61e3838140d3fb61d71bac',
    messagingSenderId: '496638177733',
    projectId: 'reports-app-dc046',
    storageBucket: 'reports-app-dc046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTAEe27GRZQ4bYJIIKqhcW1KlgxWKeNLE',
    appId: '1:496638177733:ios:573805a24087eaf7d71bac',
    messagingSenderId: '496638177733',
    projectId: 'reports-app-dc046',
    storageBucket: 'reports-app-dc046.firebasestorage.app',
    iosBundleId: 'com.example.seiyunReportsApp',
  );
}
